article daan-15-helpful-javascript-one-liners has been added
devSchacht/translations pull request #261
Opened 2021-02-03 17:50 UTC by imgVOID

2021-02-05 07:31 UTC, amel-true requested changes

2021-02-05 07:31 UTC, amel-true commented on articles/daan-15-helpful-javascript-one-liners/README.md
> +let nember = doSomeCalculation()
```suggestion
let number = doSomeCalculation()
```

2021-02-06 22:16 UTC, imgVOID commented
Здравствуйте, ошибки еще есть? Number вроде бы было исправлено https://github.com/devSchacht/translations/pull/261/commits/14d4752d74fe50ca04e06f9bc95cef50fd3297b8

2021-02-07 14:17 UTC, amel-true commented
> Здравствуйте, ошибки еще есть? Number вроде бы было исправлено [14d4752](https://github.com/devSchacht/translations/commit/14d4752d74fe50ca04e06f9bc95cef50fd3297b8)

Больше не нашёл, можно отправлять на Medium :)

2021-02-07 14:17 UTC, merged